### ISSUE TITLE
not found core_settings_min.gradle

### ISSUE THREAD

**Issue by roycep93** [ologe/canaree-music-player#12]
core_settings_min.gradle

ERROR: Could not read script '....\canaree-music-player\Users\eugeniuolog\AndroidStudioProjects\ExoPlayer\core_settings_min.gradle' as it does not exist.

Can you please update with sample code

**Comment by ologe** [comment]
Open `setting.gradle` in your project and then update:
```
gradle.ext.exoplayerRoot = '/Users/eugeniuolog/AndroidStudioProjects/ExoPlayer'
apply from: new File(gradle.ext.exoplayerRoot, 'core_settings_min.gradle')
```
to 
```
gradle.ext.exoplayerRoot = 'the path on your machine to exoplayer'
apply from: new File(gradle.ext.exoplayerRoot, 'core_settings.gradle')
```

**Comment by roycep93** [comment]
core_settings NOT EXIST in this code
 after fix some error then get bellow error while build..



> Task :data:kaptFullDebugKotlin FAILED
e: F:\github\canaree-music-player\data\build\tmp\kapt3\stubs\fullDebug\dev\olog\data\api\lastfm\LastFmService.java:20: error: element value must be a constant expression
    @retrofit2.http.GET(value = null)
                                ^
e: F:\github\canaree-music-player\data\build\tmp\kapt3\stubs\fullDebug\dev\olog\data\api\lastfm\LastFmService.java:31: error: element value must be a constant expression
    @retrofit2.http.GET(value = null)
                                ^
e: F:\github\canaree-music-player\data\build\tmp\kapt3\stubs\fullDebug\dev\olog\data\api\lastfm\LastFmService.java:42: error: element value must be a constant expression
    @retrofit2.http.GET(value = null)
                                ^
e: F:\github\canaree-music-player\data\build\tmp\kapt3\stubs\fullDebug\dev\olog\data\api\lastfm\LastFmService.java:53: error: element value must be a constant expression
    @retrofit2.http.GET(value = null)
                                ^
e: F:\github\canaree-music-player\data\build\tmp\kapt3\stubs\fullDebug\dev\olog\data\api\lastfm\LastFmService.java:62: error: element value must be a constant expression
    @retrofit2.http.GET(value = null)
                                ^
e: F:\github\canaree-music-player\data\build\tmp\kapt3\stubs\fullDebug\dev\olog\data\api\lastfm\LastFmService.java:75: error: element value must be a constant expression
    @retrofit2.http.GET(value = null)
                                ^
e: java.lang.IllegalStateException: Should not be called!
	at org.jetbrains.kotlin.types.ErrorUtils$1.getPackage(ErrorUtils.java:93)
	at org.jetbrains.kotlin.descriptors.DescriptorUtilKt.resolveClassByFqName(descriptorUtil.kt:21)
	at org.jetbrains.kotlin.resolve.checkers.ExperimentalUsageChecker$Companion$checkCompilerArguments$1.invoke(ExperimentalUsageChecker.kt:224)
	at org.jetbrains.kotlin.resolve.checkers.ExperimentalUsageChecker$Companion.checkCompilerArguments(ExperimentalUsageChecker.kt:247)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:108)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:546)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:177)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:164)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:54)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:104)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1558)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':data:kaptFullDebugKotlin'.
> Internal compiler error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 50s
168 actionable tasks: 4 executed, 164 up-to-date

**Comment by ologe** [comment]
`core_settings.gradle` is from [here](https://github.com/google/ExoPlayer/blob/release-v2/core_settings.gradle). 
In order to compile you have to clone first [ExoPlayer](https://github.com/google/ExoPlayer). 
Then open your fork of Canaree and update `settings.gradle`.
