### ISSUE TITLE
Bug found in 	 Canaree (Music Player) The application crash when I try to open any Albums Songs

### ISSUE THREAD

**Issue by saraji-ali** [ologe/canaree-music-player#2]
# Project Information

* Repository: https://github.com/ologe/canaree-music-player
* Project Name:  canaree-music-player

# Expected behavior

The application should not crash when I go to the album and open any song

# Actual behavior

 The application crash when I try to open any Albums Songs

# How to reproduce

1-[Download](https://play.google.com/store/apps/details?id=dev.olog.msc) the latest application
2-install and open the application
3- click on ALBUMS
4-  open any song
5-  see the error
* Browser/App version:  Current Version 2.1.1
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug
![20190505_183814](https://user-images.githubusercontent.com/50115498/57194988-30bfba80-6f02-11e9-8b21-a28a06d84a3c.gif)

# My Github Account
https://github.com/facebook-786

# Logcat

<pre><code>D/AndroidRuntime(17783): Shutting down VM

E/AndroidRuntime(17783): FATAL EXCEPTION: main

E/AndroidRuntime(17783): Process: dev.olog.msc, PID: 17783

E/AndroidRuntime(17783): android.view.InflateException: Binary XML file line #138: Error inflating class com.google.android.material.textfield.TextInputLayout

E/AndroidRuntime(17783): 	at android.view.LayoutInflater.createView(LayoutInflater.java:633)

E/AndroidRuntime(17783): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)

E/AndroidRuntime(17783): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)

E/AndroidRuntime(17783): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)

E/AndroidRuntime(17783): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)

E/AndroidRuntime(17783): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)

E/AndroidRuntime(17783): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)

E/AndroidRuntime(17783): 	at dev.olog.msc.presentation.base.BaseFragment.onCreateView(SourceFile:18)

E/AndroidRuntime(17783): 	at androidx.fragment.app.Fragment.a(SourceFile:2439)

E/AndroidRuntime(17783): 	at androidx.fragment.app.nul.a(SourceFile:1460)

E/AndroidRuntime(17783): 	at androidx.fragment.app.nul.b(SourceFile:2646)

E/AndroidRuntime(17783): 	at androidx.fragment.app.nul.a(SourceFile:2416)

E/AndroidRuntime(17783): 	at androidx.fragment.app.nul.b(SourceFile:2372)

E/AndroidRuntime(17783): 	at androidx.fragment.app.nul.b(SourceFile:2273)

E/AndroidRuntime(17783): 	at androidx.fragment.app.nul$1.run(SourceFile:733)

E/AndroidRuntime(17783): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(17783): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(17783): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(17783): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(17783): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(17783): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(17783): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(17783): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

E/AndroidRuntime(17783): Caused by: java.lang.reflect.InvocationTargetException

E/AndroidRuntime(17783): 	at java.lang.reflect.Constructor.newInstance(Native Method)

E/AndroidRuntime(17783): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)

E/AndroidRuntime(17783): 	at android.view.LayoutInflater.createView(LayoutInflater.java:607)

E/AndroidRuntime(17783): 	... 22 more

E/AndroidRuntime(17783): Caused by: android.content.res.Resources$NotFoundException: File res/drawable-v21/design_password_eye.xml from drawable resource ID #0x7f0800a9

E/AndroidRuntime(17783): 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2946)

E/AndroidRuntime(17783): 	at android.content.res.Resources.loadDrawable(Resources.java:2821)

E/AndroidRuntime(17783): 	at android.content.res.Resources.getDrawable(Resources.java:1050)

E/AndroidRuntime(17783): 	at android.content.res.Resources.getDrawable(Resources.java:1032)

E/AndroidRuntime(17783): 	at android.content.Context.getDrawable(Context.java:403)

E/AndroidRuntime(17783): 	at androidx.core.content.ContextCompat.getDrawable(SourceFile:463)

E/AndroidRuntime(17783): 	at androidx.appcompat.widget.AppCompatDrawableManager.a(SourceFile:203)

E/AndroidRuntime(17783): 	at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(SourceFile:191)

E/AndroidRuntime(17783): 	at androidx.appcompat.content.res.AppCompatResources.getDrawable(SourceFile:102)

E/AndroidRuntime(17783): 	at androidx.appcompat.widget.TintTypedArray.getDrawable(SourceFile:76)

E/AndroidRuntime(17783): 	at com.google.android.material.textfield.TextInputLayout.<init>(SourceFile:344)

E/AndroidRuntime(17783): 	at com.google.android.material.textfield.TextInputLayout.<init>(SourceFile:247)

E/AndroidRuntime(17783): 	... 25 more

E/AndroidRuntime(17783): Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f0800a7

E/AndroidRuntime(17783): 	at android.content.res.Resources.getResourceName(Resources.java:2413)

E/AndroidRuntime(17783): 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2908)

E/AndroidRuntime(17783): 	at android.content.res.Resources.loadDrawable(Resources.java:2821)

E/AndroidRuntime(17783): 	at android.content.res.Resources.loadDrawable(Resources.java:2670)

E/AndroidRuntime(17783): 	at android.content.res.TypedArray.getDrawable(TypedArray.java:761)

E/AndroidRuntime(17783): 	at android.graphics.drawable.AnimatedStateListDrawable.parseItem(AnimatedStateListDrawable.java:503)

E/AndroidRuntime(17783): 	at android.graphics.drawable.AnimatedStateListDrawable.inflateChildElements(AnimatedStateListDrawable.java:452)

E/AndroidRuntime(17783): 	at android.graphics.drawable.AnimatedStateListDrawable.inflate(AnimatedStateListDrawable.java:384)

E/AndroidRuntime(17783): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1128)

E/AndroidRuntime(17783): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1032)

E/AndroidRuntime(17783): 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2936)

E/AndroidRuntime(17783): 	... 36 more
</code></pre>

**Comment by saraji-ali** [comment]
Sir @ologe please review my post
